#!/bin/sh /etc/rc.common

START=99
STOP=99

start() {
    echo "starting netaidkit."
}

stop() {
    echo "stopping netaidkit."
}

boot() {
    # Clear LEDS
    echo "0" > /sys/class/leds/gl-connect\:green\:lan/brightness
    echo "0" > /sys/class/leds/gl-connect\:red\:wlan/brightness

    # Start nakd
    (/usr/bin/nakd &>/dev/null) &

    # Set domain socket permissions
    chgrp www-data /run/nakd
    chmod g+w /run/nakd
}
